root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

# Air configuration for Golang
[build]
cmd = "go build -o main ./cmd/server"
bin = "./main"
include_ext = ["go"]
exclude_dir = ["vendor"]
exclude_file = []

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
